### ISSUE TITLE
Università di Oxford in FP7: c'è due volte con ID unici diversi ?!?

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/eu-research-funding-network#3]
THE CHANCELLOR, MASTERS AND SCHOLARS OF THE UNIVERSITY OF OXFORD è presente in FP7 due volte.
- una con ID 999984350, cioè il PIC
- una con ID 1f59b06c2399697d3f6721b4f489f5bc, cioè quello generato da Stefano durante la pulitura dati. 

È solo un errore o c'è un motivo?

**Comment by stefanoduri** [comment]
nel file delle organizzazioni sfortunatamente appare a volte con ID, altre senza. In questo secondo caso assume un id calcolato

**Comment by stefanoduri** [comment]
direi che è il risultato di un incrocio perverso di dati presenti/assenti/diversi tra i vari progetti. Si può cercare di ovviare facendo un ulteriore dedup su nome dell'organizzazione+country.

**Comment by albertocottica** [comment]
Chiuso via pull request #4
