### ISSUE TITLE
Conflitto nella pull request

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/eu-research-funding-network#6]
Dopo molto lavoro sul mio branch, ho fatto una pull request. Ci sono dei conflitti, che credo siano dovuti al fatto che Stefano ha ricommittato i dati ripuliti, poi io me li sono ripresi ma li ho dovuti cambiare a causa dell'issue #2 . 

Ho provato a usare la linea di comando per il merge, ma ottengo un messaggio di errore al primo passaggio: 

`xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
`
Cercando in rete, ho scoperto che OSX El Capitàn rompe i developer tools: https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/

Prima di imbarcarmi in quella procedura, però, vorrei essere sicuro che ce n'è bisogno! Inoltre, forse facciamo prima se qualcuno di voi che non ha problemi con git mi accetta la pull request. Mi date una mano?

**Comment by dottorblaster** [comment]
Dovresti poter risolvere semplicemente con un 

``` bash
$ xcode-select --install
```

**Comment by albertocottica** [comment]
grazie @dottorblaster ! Adesso i dev tools funzionano. Però continuo a non riuscire a fare il merge: anche i comandi di linea trovano il conflitto e mi bloccano. 

Ho provato a leggere questo articolo, ma suggerisce delle soluzioni che non vanno bene (aggiungere o togliere files). Io vorrei sovrascrivere il mio branch (che è quello più aggiornato) al master. 

https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by dottorblaster** [comment]
Prova

``` bash
$ git fetch origin master
$ git merge -s recursive -X ours origin/master
```

**Comment by albertocottica** [comment]
No. Guarda, è che io non so come si fa a risolvere i conflitti. Basterebbe un buon instructable, che partisse dal principio. Ho trovato [questo](https://githowto.com/resolving_conflicts), ma non fa al caso mio perché c'è conflitto in un solo file. Nel mio è tutta la repo, decine di files...

```
error: merge is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

**Comment by dottorblaster** [comment]
Eh dovresti fare un undo massiccio del pull che hai fatto prima, però ora non so nemmeno a che punto sei :/

**Comment by albertocottica** [comment]
Non mi pare che sia possibile fare undo prima del merge. Esiste un revert, che puoi fare _dopo_ che la pull request è stata accettata. In alternativa, posso marcare questa pull request come "done". O ti riferisci alla pull request prima della mia?

**Comment by albertocottica** [comment]
Risolto facendo un nuovo ramo, copiando tutte le cartelle nel nuovo ramo e facendo una pull request. Un po' rozzo ma ha funzionato.
