### ISSUE TITLE
H2020DeathStar.json edit

### ISSUE THREAD

**Issue by Federicopvs** [spaghetti-open-data/eu-research-funding-network#7]
Allberto avrei bisogno che il file sia strutturato in modo leggermente diverso. Ora la struttura e' la seguente:

```
{"nodes" : 
    [
         {"node"  : 
               {"name":"name01", "ID":"ID01", ... , etc } 
               {"name":"name02", "ID":"ID02", ... , etc }
         }
    ]
}
{"edges":
    [
         {"edge" : {"source":""source01", "target":"target01", ... , etc } }
    ]
}
```

Io invece lo vorrei cosi'

```
{"nodes" : 
    [
          {"name":"name01", "ID":"ID01", ... , etc } 
          {"name":"name02", "ID":"ID02", ... , etc }
    ]
}
{"edges":
    [
         {"source":""source01", "target":"target01", ... , etc } 
    ]
}
```

OPTIONAL (1):
Visto che ci sei ti chiederei di cambiare un attimo i nomi degli output (anche se volendo si potrebbe fare in un secondo momento. Metto dei suggerimenti per quelli che vorrei cambiare, l'importante e' che siano corti.
- node:
  - number of projects -> numProj
  - number of organisations for which this organisation is the only stable H2020 partner -> dependentOrgs
- edge:
  - sum of the budgets of all the projects that these two partners have co-participated in -> collaborations
  - number of projects that these two partners have co-participated in -> collBudget

OPTIONAL(2):
Per ogni node mancherebbero anche gruppo, citta', paese, e url sito.

**Comment by albertocottica** [comment]
Fatto con commit eed6427. 

Devo capire perché i paesi non vengono su dal primo import, ma lì ci vuole un po' di più.
